sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-unittests
    - python: 3.3
      env: TOXENV=py33-unittests
    - python: 3.4
      env: TOXENV=py34-unittests
    - python: 3.5
      env: TOXENV=py35-unittests
    - python: 2.7
      env: TOXENV=lint
install:
  - pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - codecov
