sudo: false
language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27-unittests
  - python: 3.3
    env: TOXENV=py33-unittests
  - python: 3.4
    env: TOXENV=py34-unittests
  - python: 3.5
    env: TOXENV=py35-unittests
  - python: 3.6
    env: TOXENV=py36-unittests
  - python: 3.6
    env: TOXENV=lint
  - python: 2.7
    env: TOXENV=documents
addons:
  apt:
    packages:
    - aspell
    - aspell-en
install:
- pip install tox
- pip install codecov
script:
- tox
after_success:
- codecov
deploy:
  - provider: pypi
    user: facelessuser
    server: https://upload.pypi.org/legacy/
    password:
      secure: S/7VvUM4b8dViV5YtOJOE3+w8u/n0nV3b3nyYzcgdetxYp9ppUq7wRZEwWRXGkLH7LPHxprq8n7EGHBVpfDHbesUqj+m93OPVNBlNy8Uh3p6bUlaI0f8MW2zAPq04oOHZ0mbWuDe34aHW3IEoCFCFL5gUAgx7cBIjcHPFFyTPsHnQGAVf/cLHfEE+OtJgUeFLgdBKehbcN9P7W96o8TMrJL6bQObytzzLUFN0LfkqBmqnZH+7g1Hlxw3k9ajSC2edLjCDmuEQy+NYsVrW6/XB9vzNzYA1/JREdP+6IEQ+V4temRzgVWNgWjrl83Du+c73Cc/DkVPoOw/udAHqFk/nNYQCZJbzZnuQxqrp/MDKZxmJzmspDX7PCQV3Mw0pxYTbE/3bWSVVPfwi2VCbaOkELndHBOCBXK0U12exlg9vidJA+18M5TkiNIBCjkWAI9uUeLxfQcW9q7hWeiKgbD2VJPpp4V4TjtTAAMEIyq2Eie2uoreKL07Q82QcKKqudKZWaUl++nh/ZNo5u8X0K2YZQWOD9iKrsCOgpov8Bh9Kz57QpBTDgx6l1NTovmbQ4v1vFgGZVx4MnhpQgIqzHU+5Bb8E/ar0FtsCEfG0m5yLwKA0SOrX8vSAlTu8w3yN+Q/pbbetVsvMR3pCeh8bu+s742wS6Llx5RxALi8nJygm6k=
    distributions: "sdist bdist_wheel"
    skip_upload_docs: true
    on:
      tags: true
      repo: facelessuser/pymdown-extensions
      condition: "$TOXENV = documents"
  - provider: pages
    github_token: $GITHUB_TOKEN
    name: $GITHUB_USER
    email: $GITHUB_EMAIL
    skip_cleanup: true
    local_dir: site
    on:
      tags: true
      repo: facelessuser/pymdown-extensions
      condition: "$TOXENV = documents"
