name: new pull
on:
  pull_request:
    types: [opened, reopened]

jobs:
  needs-review:
    name: Apply needs-review label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Apply needs-review label
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: label needs-review
